/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPlaygroundRouteImport } from './routes/_authenticated.playground'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedPlaygroundIndexRouteImport } from './routes/_authenticated.playground.index'
import { Route as AuthenticatedPlaygroundTopicsRouteImport } from './routes/_authenticated.playground.topics'
import { Route as AuthenticatedPlaygroundReportsRouteImport } from './routes/_authenticated.playground.reports'
import { Route as AuthenticatedPlaygroundFlashcardsRouteImport } from './routes/_authenticated.playground.flashcards'
import { Route as AuthenticatedPlaygroundChatsRouteImport } from './routes/_authenticated.playground.chats'
import { Route as AuthenticatedPlaygroundTopicsIndexRouteImport } from './routes/_authenticated.playground.topics.index'
import { Route as AuthenticatedPlaygroundReportsIndexRouteImport } from './routes/_authenticated.playground.reports.index'
import { Route as AuthenticatedPlaygroundFlashcardsIndexRouteImport } from './routes/_authenticated.playground.flashcards.index'
import { Route as AuthenticatedPlaygroundChatsIndexRouteImport } from './routes/_authenticated.playground.chats.index'
import { Route as AuthenticatedPlaygroundTopicsTopicIdRouteImport } from './routes/_authenticated.playground.topics.$topicId'
import { Route as AuthenticatedPlaygroundSessionTopicIdRouteImport } from './routes/_authenticated.playground.session.$topicId'
import { Route as AuthenticatedPlaygroundReportsReportIdRouteImport } from './routes/_authenticated.playground.reports.$reportId'
import { Route as AuthenticatedPlaygroundFlashcardsTopicIdRouteImport } from './routes/_authenticated.playground.flashcards.$topicId'
import { Route as AuthenticatedPlaygroundChatsSessionIdRouteImport } from './routes/_authenticated.playground.chats.$sessionId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlaygroundRoute = AuthenticatedPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlaygroundIndexRoute =
  AuthenticatedPlaygroundIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlaygroundRoute,
  } as any)
const AuthenticatedPlaygroundTopicsRoute =
  AuthenticatedPlaygroundTopicsRouteImport.update({
    id: '/topics',
    path: '/topics',
    getParentRoute: () => AuthenticatedPlaygroundRoute,
  } as any)
const AuthenticatedPlaygroundReportsRoute =
  AuthenticatedPlaygroundReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedPlaygroundRoute,
  } as any)
const AuthenticatedPlaygroundFlashcardsRoute =
  AuthenticatedPlaygroundFlashcardsRouteImport.update({
    id: '/flashcards',
    path: '/flashcards',
    getParentRoute: () => AuthenticatedPlaygroundRoute,
  } as any)
const AuthenticatedPlaygroundChatsRoute =
  AuthenticatedPlaygroundChatsRouteImport.update({
    id: '/chats',
    path: '/chats',
    getParentRoute: () => AuthenticatedPlaygroundRoute,
  } as any)
const AuthenticatedPlaygroundTopicsIndexRoute =
  AuthenticatedPlaygroundTopicsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlaygroundTopicsRoute,
  } as any)
const AuthenticatedPlaygroundReportsIndexRoute =
  AuthenticatedPlaygroundReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlaygroundReportsRoute,
  } as any)
const AuthenticatedPlaygroundFlashcardsIndexRoute =
  AuthenticatedPlaygroundFlashcardsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlaygroundFlashcardsRoute,
  } as any)
const AuthenticatedPlaygroundChatsIndexRoute =
  AuthenticatedPlaygroundChatsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlaygroundChatsRoute,
  } as any)
const AuthenticatedPlaygroundTopicsTopicIdRoute =
  AuthenticatedPlaygroundTopicsTopicIdRouteImport.update({
    id: '/$topicId',
    path: '/$topicId',
    getParentRoute: () => AuthenticatedPlaygroundTopicsRoute,
  } as any)
const AuthenticatedPlaygroundSessionTopicIdRoute =
  AuthenticatedPlaygroundSessionTopicIdRouteImport.update({
    id: '/session/$topicId',
    path: '/session/$topicId',
    getParentRoute: () => AuthenticatedPlaygroundRoute,
  } as any)
const AuthenticatedPlaygroundReportsReportIdRoute =
  AuthenticatedPlaygroundReportsReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => AuthenticatedPlaygroundReportsRoute,
  } as any)
const AuthenticatedPlaygroundFlashcardsTopicIdRoute =
  AuthenticatedPlaygroundFlashcardsTopicIdRouteImport.update({
    id: '/$topicId',
    path: '/$topicId',
    getParentRoute: () => AuthenticatedPlaygroundFlashcardsRoute,
  } as any)
const AuthenticatedPlaygroundChatsSessionIdRoute =
  AuthenticatedPlaygroundChatsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedPlaygroundChatsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/playground': typeof AuthenticatedPlaygroundRouteWithChildren
  '/playground/chats': typeof AuthenticatedPlaygroundChatsRouteWithChildren
  '/playground/flashcards': typeof AuthenticatedPlaygroundFlashcardsRouteWithChildren
  '/playground/reports': typeof AuthenticatedPlaygroundReportsRouteWithChildren
  '/playground/topics': typeof AuthenticatedPlaygroundTopicsRouteWithChildren
  '/playground/': typeof AuthenticatedPlaygroundIndexRoute
  '/playground/chats/$sessionId': typeof AuthenticatedPlaygroundChatsSessionIdRoute
  '/playground/flashcards/$topicId': typeof AuthenticatedPlaygroundFlashcardsTopicIdRoute
  '/playground/reports/$reportId': typeof AuthenticatedPlaygroundReportsReportIdRoute
  '/playground/session/$topicId': typeof AuthenticatedPlaygroundSessionTopicIdRoute
  '/playground/topics/$topicId': typeof AuthenticatedPlaygroundTopicsTopicIdRoute
  '/playground/chats/': typeof AuthenticatedPlaygroundChatsIndexRoute
  '/playground/flashcards/': typeof AuthenticatedPlaygroundFlashcardsIndexRoute
  '/playground/reports/': typeof AuthenticatedPlaygroundReportsIndexRoute
  '/playground/topics/': typeof AuthenticatedPlaygroundTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/playground': typeof AuthenticatedPlaygroundIndexRoute
  '/playground/chats/$sessionId': typeof AuthenticatedPlaygroundChatsSessionIdRoute
  '/playground/flashcards/$topicId': typeof AuthenticatedPlaygroundFlashcardsTopicIdRoute
  '/playground/reports/$reportId': typeof AuthenticatedPlaygroundReportsReportIdRoute
  '/playground/session/$topicId': typeof AuthenticatedPlaygroundSessionTopicIdRoute
  '/playground/topics/$topicId': typeof AuthenticatedPlaygroundTopicsTopicIdRoute
  '/playground/chats': typeof AuthenticatedPlaygroundChatsIndexRoute
  '/playground/flashcards': typeof AuthenticatedPlaygroundFlashcardsIndexRoute
  '/playground/reports': typeof AuthenticatedPlaygroundReportsIndexRoute
  '/playground/topics': typeof AuthenticatedPlaygroundTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/playground': typeof AuthenticatedPlaygroundRouteWithChildren
  '/_authenticated/playground/chats': typeof AuthenticatedPlaygroundChatsRouteWithChildren
  '/_authenticated/playground/flashcards': typeof AuthenticatedPlaygroundFlashcardsRouteWithChildren
  '/_authenticated/playground/reports': typeof AuthenticatedPlaygroundReportsRouteWithChildren
  '/_authenticated/playground/topics': typeof AuthenticatedPlaygroundTopicsRouteWithChildren
  '/_authenticated/playground/': typeof AuthenticatedPlaygroundIndexRoute
  '/_authenticated/playground/chats/$sessionId': typeof AuthenticatedPlaygroundChatsSessionIdRoute
  '/_authenticated/playground/flashcards/$topicId': typeof AuthenticatedPlaygroundFlashcardsTopicIdRoute
  '/_authenticated/playground/reports/$reportId': typeof AuthenticatedPlaygroundReportsReportIdRoute
  '/_authenticated/playground/session/$topicId': typeof AuthenticatedPlaygroundSessionTopicIdRoute
  '/_authenticated/playground/topics/$topicId': typeof AuthenticatedPlaygroundTopicsTopicIdRoute
  '/_authenticated/playground/chats/': typeof AuthenticatedPlaygroundChatsIndexRoute
  '/_authenticated/playground/flashcards/': typeof AuthenticatedPlaygroundFlashcardsIndexRoute
  '/_authenticated/playground/reports/': typeof AuthenticatedPlaygroundReportsIndexRoute
  '/_authenticated/playground/topics/': typeof AuthenticatedPlaygroundTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/onboarding'
    | '/playground'
    | '/playground/chats'
    | '/playground/flashcards'
    | '/playground/reports'
    | '/playground/topics'
    | '/playground/'
    | '/playground/chats/$sessionId'
    | '/playground/flashcards/$topicId'
    | '/playground/reports/$reportId'
    | '/playground/session/$topicId'
    | '/playground/topics/$topicId'
    | '/playground/chats/'
    | '/playground/flashcards/'
    | '/playground/reports/'
    | '/playground/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/onboarding'
    | '/playground'
    | '/playground/chats/$sessionId'
    | '/playground/flashcards/$topicId'
    | '/playground/reports/$reportId'
    | '/playground/session/$topicId'
    | '/playground/topics/$topicId'
    | '/playground/chats'
    | '/playground/flashcards'
    | '/playground/reports'
    | '/playground/topics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/onboarding'
    | '/_authenticated/playground'
    | '/_authenticated/playground/chats'
    | '/_authenticated/playground/flashcards'
    | '/_authenticated/playground/reports'
    | '/_authenticated/playground/topics'
    | '/_authenticated/playground/'
    | '/_authenticated/playground/chats/$sessionId'
    | '/_authenticated/playground/flashcards/$topicId'
    | '/_authenticated/playground/reports/$reportId'
    | '/_authenticated/playground/session/$topicId'
    | '/_authenticated/playground/topics/$topicId'
    | '/_authenticated/playground/chats/'
    | '/_authenticated/playground/flashcards/'
    | '/_authenticated/playground/reports/'
    | '/_authenticated/playground/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/playground': {
      id: '/_authenticated/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AuthenticatedPlaygroundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/playground/': {
      id: '/_authenticated/playground/'
      path: '/'
      fullPath: '/playground/'
      preLoaderRoute: typeof AuthenticatedPlaygroundIndexRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRoute
    }
    '/_authenticated/playground/topics': {
      id: '/_authenticated/playground/topics'
      path: '/topics'
      fullPath: '/playground/topics'
      preLoaderRoute: typeof AuthenticatedPlaygroundTopicsRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRoute
    }
    '/_authenticated/playground/reports': {
      id: '/_authenticated/playground/reports'
      path: '/reports'
      fullPath: '/playground/reports'
      preLoaderRoute: typeof AuthenticatedPlaygroundReportsRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRoute
    }
    '/_authenticated/playground/flashcards': {
      id: '/_authenticated/playground/flashcards'
      path: '/flashcards'
      fullPath: '/playground/flashcards'
      preLoaderRoute: typeof AuthenticatedPlaygroundFlashcardsRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRoute
    }
    '/_authenticated/playground/chats': {
      id: '/_authenticated/playground/chats'
      path: '/chats'
      fullPath: '/playground/chats'
      preLoaderRoute: typeof AuthenticatedPlaygroundChatsRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRoute
    }
    '/_authenticated/playground/topics/': {
      id: '/_authenticated/playground/topics/'
      path: '/'
      fullPath: '/playground/topics/'
      preLoaderRoute: typeof AuthenticatedPlaygroundTopicsIndexRouteImport
      parentRoute: typeof AuthenticatedPlaygroundTopicsRoute
    }
    '/_authenticated/playground/reports/': {
      id: '/_authenticated/playground/reports/'
      path: '/'
      fullPath: '/playground/reports/'
      preLoaderRoute: typeof AuthenticatedPlaygroundReportsIndexRouteImport
      parentRoute: typeof AuthenticatedPlaygroundReportsRoute
    }
    '/_authenticated/playground/flashcards/': {
      id: '/_authenticated/playground/flashcards/'
      path: '/'
      fullPath: '/playground/flashcards/'
      preLoaderRoute: typeof AuthenticatedPlaygroundFlashcardsIndexRouteImport
      parentRoute: typeof AuthenticatedPlaygroundFlashcardsRoute
    }
    '/_authenticated/playground/chats/': {
      id: '/_authenticated/playground/chats/'
      path: '/'
      fullPath: '/playground/chats/'
      preLoaderRoute: typeof AuthenticatedPlaygroundChatsIndexRouteImport
      parentRoute: typeof AuthenticatedPlaygroundChatsRoute
    }
    '/_authenticated/playground/topics/$topicId': {
      id: '/_authenticated/playground/topics/$topicId'
      path: '/$topicId'
      fullPath: '/playground/topics/$topicId'
      preLoaderRoute: typeof AuthenticatedPlaygroundTopicsTopicIdRouteImport
      parentRoute: typeof AuthenticatedPlaygroundTopicsRoute
    }
    '/_authenticated/playground/session/$topicId': {
      id: '/_authenticated/playground/session/$topicId'
      path: '/session/$topicId'
      fullPath: '/playground/session/$topicId'
      preLoaderRoute: typeof AuthenticatedPlaygroundSessionTopicIdRouteImport
      parentRoute: typeof AuthenticatedPlaygroundRoute
    }
    '/_authenticated/playground/reports/$reportId': {
      id: '/_authenticated/playground/reports/$reportId'
      path: '/$reportId'
      fullPath: '/playground/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedPlaygroundReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedPlaygroundReportsRoute
    }
    '/_authenticated/playground/flashcards/$topicId': {
      id: '/_authenticated/playground/flashcards/$topicId'
      path: '/$topicId'
      fullPath: '/playground/flashcards/$topicId'
      preLoaderRoute: typeof AuthenticatedPlaygroundFlashcardsTopicIdRouteImport
      parentRoute: typeof AuthenticatedPlaygroundFlashcardsRoute
    }
    '/_authenticated/playground/chats/$sessionId': {
      id: '/_authenticated/playground/chats/$sessionId'
      path: '/$sessionId'
      fullPath: '/playground/chats/$sessionId'
      preLoaderRoute: typeof AuthenticatedPlaygroundChatsSessionIdRouteImport
      parentRoute: typeof AuthenticatedPlaygroundChatsRoute
    }
  }
}

interface AuthenticatedPlaygroundChatsRouteChildren {
  AuthenticatedPlaygroundChatsSessionIdRoute: typeof AuthenticatedPlaygroundChatsSessionIdRoute
  AuthenticatedPlaygroundChatsIndexRoute: typeof AuthenticatedPlaygroundChatsIndexRoute
}

const AuthenticatedPlaygroundChatsRouteChildren: AuthenticatedPlaygroundChatsRouteChildren =
  {
    AuthenticatedPlaygroundChatsSessionIdRoute:
      AuthenticatedPlaygroundChatsSessionIdRoute,
    AuthenticatedPlaygroundChatsIndexRoute:
      AuthenticatedPlaygroundChatsIndexRoute,
  }

const AuthenticatedPlaygroundChatsRouteWithChildren =
  AuthenticatedPlaygroundChatsRoute._addFileChildren(
    AuthenticatedPlaygroundChatsRouteChildren,
  )

interface AuthenticatedPlaygroundFlashcardsRouteChildren {
  AuthenticatedPlaygroundFlashcardsTopicIdRoute: typeof AuthenticatedPlaygroundFlashcardsTopicIdRoute
  AuthenticatedPlaygroundFlashcardsIndexRoute: typeof AuthenticatedPlaygroundFlashcardsIndexRoute
}

const AuthenticatedPlaygroundFlashcardsRouteChildren: AuthenticatedPlaygroundFlashcardsRouteChildren =
  {
    AuthenticatedPlaygroundFlashcardsTopicIdRoute:
      AuthenticatedPlaygroundFlashcardsTopicIdRoute,
    AuthenticatedPlaygroundFlashcardsIndexRoute:
      AuthenticatedPlaygroundFlashcardsIndexRoute,
  }

const AuthenticatedPlaygroundFlashcardsRouteWithChildren =
  AuthenticatedPlaygroundFlashcardsRoute._addFileChildren(
    AuthenticatedPlaygroundFlashcardsRouteChildren,
  )

interface AuthenticatedPlaygroundReportsRouteChildren {
  AuthenticatedPlaygroundReportsReportIdRoute: typeof AuthenticatedPlaygroundReportsReportIdRoute
  AuthenticatedPlaygroundReportsIndexRoute: typeof AuthenticatedPlaygroundReportsIndexRoute
}

const AuthenticatedPlaygroundReportsRouteChildren: AuthenticatedPlaygroundReportsRouteChildren =
  {
    AuthenticatedPlaygroundReportsReportIdRoute:
      AuthenticatedPlaygroundReportsReportIdRoute,
    AuthenticatedPlaygroundReportsIndexRoute:
      AuthenticatedPlaygroundReportsIndexRoute,
  }

const AuthenticatedPlaygroundReportsRouteWithChildren =
  AuthenticatedPlaygroundReportsRoute._addFileChildren(
    AuthenticatedPlaygroundReportsRouteChildren,
  )

interface AuthenticatedPlaygroundTopicsRouteChildren {
  AuthenticatedPlaygroundTopicsTopicIdRoute: typeof AuthenticatedPlaygroundTopicsTopicIdRoute
  AuthenticatedPlaygroundTopicsIndexRoute: typeof AuthenticatedPlaygroundTopicsIndexRoute
}

const AuthenticatedPlaygroundTopicsRouteChildren: AuthenticatedPlaygroundTopicsRouteChildren =
  {
    AuthenticatedPlaygroundTopicsTopicIdRoute:
      AuthenticatedPlaygroundTopicsTopicIdRoute,
    AuthenticatedPlaygroundTopicsIndexRoute:
      AuthenticatedPlaygroundTopicsIndexRoute,
  }

const AuthenticatedPlaygroundTopicsRouteWithChildren =
  AuthenticatedPlaygroundTopicsRoute._addFileChildren(
    AuthenticatedPlaygroundTopicsRouteChildren,
  )

interface AuthenticatedPlaygroundRouteChildren {
  AuthenticatedPlaygroundChatsRoute: typeof AuthenticatedPlaygroundChatsRouteWithChildren
  AuthenticatedPlaygroundFlashcardsRoute: typeof AuthenticatedPlaygroundFlashcardsRouteWithChildren
  AuthenticatedPlaygroundReportsRoute: typeof AuthenticatedPlaygroundReportsRouteWithChildren
  AuthenticatedPlaygroundTopicsRoute: typeof AuthenticatedPlaygroundTopicsRouteWithChildren
  AuthenticatedPlaygroundIndexRoute: typeof AuthenticatedPlaygroundIndexRoute
  AuthenticatedPlaygroundSessionTopicIdRoute: typeof AuthenticatedPlaygroundSessionTopicIdRoute
}

const AuthenticatedPlaygroundRouteChildren: AuthenticatedPlaygroundRouteChildren =
  {
    AuthenticatedPlaygroundChatsRoute:
      AuthenticatedPlaygroundChatsRouteWithChildren,
    AuthenticatedPlaygroundFlashcardsRoute:
      AuthenticatedPlaygroundFlashcardsRouteWithChildren,
    AuthenticatedPlaygroundReportsRoute:
      AuthenticatedPlaygroundReportsRouteWithChildren,
    AuthenticatedPlaygroundTopicsRoute:
      AuthenticatedPlaygroundTopicsRouteWithChildren,
    AuthenticatedPlaygroundIndexRoute: AuthenticatedPlaygroundIndexRoute,
    AuthenticatedPlaygroundSessionTopicIdRoute:
      AuthenticatedPlaygroundSessionTopicIdRoute,
  }

const AuthenticatedPlaygroundRouteWithChildren =
  AuthenticatedPlaygroundRoute._addFileChildren(
    AuthenticatedPlaygroundRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlaygroundRoute: typeof AuthenticatedPlaygroundRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlaygroundRoute: AuthenticatedPlaygroundRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
